#All the Lidars will share a same common config file
#The size of the config file list is the number of the Lidar
common:
    msg_source: 2             #@type: int  @detail: 0--not use Lidar, 1--lidar packet message come from sensor driver
                              #                     2--lidar packet message come from ROS,3--lidar points message come from ROS, 4--packets from proto, 5--points from proto
    send_packets_ros: false     #@type: bool @detail: if true, the original lidar packets message will be sent out through ROS
    send_points_ros: true     #@type: bool @detail: if true, the original lidar points message will be sent out through ROS
    send_points_proto: false 
    send_packets_proto: false

lidar:
  - driver:
      include: middle_lidar/lidar.yaml
    ros:
      ros_recv_points_topic: /rslidar_points
      ros_recv_packets_topic: /rslidar_packets
      ros_send_points_topic: /rslidar_points
      ros_send_packets_topic: /rslidar_packets
    proto:
      points_send_port: 60021
      points_recv_port: 60021
      points_send_ip: 127.0.0.1
      msop_send_port: 60022
      msop_recv_port: 60022
      difop_send_port: 60023
      difop_recv_port: 60023
      packets_send_ip: 127.0.0.1



  


